// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("IDisposableAnalyzers.Correctness", "IDISP004:Don't ignore return value of type IDisposable.", Justification = "Disposed by xunit framework.", Scope = "member", Target = "~M:Audacia.XunitExtensions.Inconclusive.InconclusiveFactDiscoverer.Discover(Xunit.Abstractions.ITestFrameworkDiscoveryOptions,Xunit.Abstractions.ITestMethod,Xunit.Abstractions.IAttributeInfo)~System.Collections.Generic.IEnumerable{Xunit.Sdk.IXunitTestCase}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("IDisposableAnalyzers.Correctness", "IDISP004:Don't ignore return value of type IDisposable.", Justification = "Disposed by xunit framework.", Scope = "member", Target = "~M:Audacia.XunitExtensions.Retry.BrittleFactDiscoverer.Discover(Xunit.Abstractions.ITestFrameworkDiscoveryOptions,Xunit.Abstractions.ITestMethod,Xunit.Abstractions.IAttributeInfo)~System.Collections.Generic.IEnumerable{Xunit.Sdk.IXunitTestCase}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("IDisposableAnalyzers.Correctness", "IDISP001:Dispose created.", Justification = "Disposal not implemented.", Scope = "member", Target = "~M:Audacia.XunitExtensions.Inconclusive.InconclusiveTheoryTestCase.RunAsync(Xunit.Abstractions.IMessageSink,Xunit.Sdk.IMessageBus,System.Object[],Xunit.Sdk.ExceptionAggregator,System.Threading.CancellationTokenSource)~System.Threading.Tasks.Task{Xunit.Sdk.RunSummary}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("IDisposableAnalyzers.Correctness", "IDISP001:Dispose created.", Justification = "Disposal not implemented.", Scope = "member", Target = "~M:Audacia.XunitExtensions.Inconclusive.InconclusiveTestCase.RunAsync(Xunit.Abstractions.IMessageSink,Xunit.Sdk.IMessageBus,System.Object[],Xunit.Sdk.ExceptionAggregator,System.Threading.CancellationTokenSource)~System.Threading.Tasks.Task{Xunit.Sdk.RunSummary}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1063:Implement IDisposable Correctly", Justification = "Disposal not implemented.", Scope = "type", Target = "~T:Audacia.XunitExtensions.Inconclusive.InconclusiveTestInterceptorMessageBus")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA1816:Dispose methods should call SuppressFinalize", Justification = "Disposal not implemented.", Scope = "member", Target = "~M:Audacia.XunitExtensions.Inconclusive.InconclusiveTestInterceptorMessageBus.Dispose")]
